# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quesresp', '0002_auto_20190716_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_multiple_responses',
            field=models.BooleanField(default=False, help_text='Designates if the question has multiple responses in the decision tree'),
        ),
    ]
