# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-03 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quesresp', '0002_auto_20190716_0607'),
    ]

    operations = [
    ]
