# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-26 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quesresp', '0003_question_has_multiple_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_feedback_question',
            field=models.BooleanField(default=False, help_text='Designates if the question is a feedback question in the decision tree'),
        ),
    ]
