# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-30 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quesresp', '0004_question_is_feedback_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='comment',
            field=models.TextField(default='', help_text='used to show comment per response if available'),
        ),
    ]
