# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-01 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quesresp', '0005_response_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='has_multiple_responses',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_feedback_question',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'select'), (2, 'checkbox'), (3, 'radio button')], default=1, help_text='type of response to be stored'),
        ),
    ]
