# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-03 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quesresp', '0003_auto_20191003_0702'),
        ('quesresp', '0006_auto_20191001_0921'),
    ]

    operations = [
    ]
