# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-03 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quesresp', '0007_merge_20191003_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='comment',
            field=models.TextField(help_text='used to show comment per response if available', null=True),
        ),
    ]
