# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-04 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quesresp', '0009_auto_20191003_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='next_default_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quesresp.Question'),
        ),
    ]
