# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quesresp', '0010_question_next_default_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='response',
            name='response_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
