# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-09 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quesresp', '0011_auto_20191009_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response_Image',
            new_name='response_image',
        ),
    ]
