# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quesresp', '0012_auto_20191009_1141'),
    ]

    operations = [
    ]
