# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('quesresp', '0014_question_next_default_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Application'),
        ),
    ]
