# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-18 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_end_url'),
        ('quesresp', '0015_auto_20191014_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='send_user_info',
            field=models.BooleanField(default=False, help_text='Designates whether the response_message sends request to vendor or not'),
        ),
    ]
