"""
Django settings for chatbot project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys
import json


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(BASE_DIR)



try:
    with open(os.path.join(BASE_DIR, 'config', 'secrets.json'), 'r') as secrets_file:
        SECRETS = json.load(secrets_file)
except IOError:
    SECRETS = {}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =  SECRETS['secretKey']


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = SECRETS['debug']
IS_GCP = SECRETS['isGCP']
ALLOWED_HOSTS = SECRETS['allowedHosts']


STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static_core')]


# Application definition

INSTALLED_APPS = SECRETS['installedApps']

MIDDLEWARE = SECRETS['middleware']

ROOT_URLCONF = SECRETS['rootUrlConf']

TEMPLATES = SECRETS['templates']

WSGI_APPLICATION = SECRETS['wsgiApplication']

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = PROJECT_DIR + '/chatbot/config/code-learning-key.json'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = SECRETS['databases']



# UPDATE mysql.user SET Password = PASSWORD('root') WHERE User = 'root'


######## LOGGING CONFIG ############################

LOGGING = SECRETS['logging']



# ######## STORAGE SETTINGS #############
# GS_BUCKET_NAME = 'learning-media-staging-189607'
# GCP_PRIVATE_MEDIA_BUCKET = 'learning--misc-staging-189607'
# GCP_STATIC_BUCKET = 'learning-static-staging-189607'
# GCP_INVOICE_BUCKET = 'learning-invoices-staging-189607'
# GCP_RESUME_BUILDER_BUCKET = 'learning--misc-staging-189607'

# ###### LOGGING SETTINGS #############
# SYSLOG_ADDRESS = '/dev/log'
# # Following is to make sure logging works with mac machines 2
# if sys.platform == "darwin":
#     SYSLOG_ADDRESS = "/var/run/syslog"
# # LOGGING['handlers']['syslog']['address'] = SYSLOG_ADDRESS


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = SECRETS['authPasswordValidators']

AUTH_USER_MODEL = SECRETS['authUserModel']


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE =SECRETS['languageCode'] 

TIME_ZONE = SECRETS['timeZone']

USE_I18N =SECRETS['useI18n']

USE_L10N = SECRETS['useL10N']

USE_TZ =SECRETS['useTz']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = SECRETS['staticUrl']

CORS_ORIGIN_ALLOW_ALL = SECRETS['corsOriginAllowAll']

CORS_ORIGIN_WHITELIST = ('*',)

MEDIA_ROOT = os.path.join(BASE_DIR,'media')

MEDIA_URL =SECRETS['mediaUrl']

SITE_DOMAIN = SECRETS['siteDomain']

DEFAULT_FILE_STORAGE = SECRETS['defaultFileStorage'] 

GS_BUCKET_NAME = SECRETS['gsBucketName'] 


PRIVATE_MEDIA_FILE_STORAGE = SECRETS['privateMediaFileStorage']
GCP_PRIVATE_MEDIA_BUCKET = SECRETS['gcpPrivateMediaBucket'] 
GCP_RESUME_BUILDER_BUCKET = SECRETS['gcpResumeBuilderBucket']
CRM_PRIVATE_MEDIA_BUCKET = SECRETS['crmPrivateMediaBucket'] 
STATICFILES_STORAGE = SECRETS['staticFilesStorage']
GS_PROJECT_ID = SECRETS['gsProjectId']
GCP_STATIC_BUCKET = SECRETS['gcpStaticBucket'] 

INVOICE_FILE_STORAGE = SECRETS['invoiceFileStorage']
GCP_INVOICE_BUCKET = SECRETS['gcpInvoiceBucket'] 

GCP_MEDIA_LOCATION = SECRETS['gcpMediaLocation'] 
GCP_STATIC_LOCATION = SECRETS['gcpStaticLocation'] 

DESKTOP_SITE_DOMAIN = SECRETS['desktopSiteDomain']
MOBILE_SITE_DOMAIN = SECRETS['mobileSiteDomain'] 

# STATIC_ROOT = os.path.join(BASE_DIR, 'static_core')


















