# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-14 09:27
from __future__ import unicode_literals

import apps.application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0005_auto_20191011_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=100, unique=True)),
                ('chatbot_icon', models.ImageField(blank=True, null=True, upload_to=apps.application.models.path_and_rename)),
                ('chatbot_title', models.CharField(blank=True, help_text='title of the chatbot', max_length=100, null=True)),
                ('script', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether a vendor is active or not')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor')),
            ],
        ),
    ]
