# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-14 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='end_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='greeting_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
