# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-18 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20191014_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='end_url',
            field=models.URLField(blank=True, help_text='url to send request to the vendor', max_length=300, null=True),
        ),
    ]
